apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bottom-grasshopper-go
  janus-idp.io/tekton: bottom-grasshopper-go
  backstage.io/kubernetes-id: bottom-grasshopper-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bottom-grasshopper-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
