apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bottom-grasshopper-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bottom-grasshopper-go 
  name: bottom-grasshopper-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bottom-grasshopper-go 
